### ISSUE TITLE
How to get hypernyms with the Go version of wordnet?

### ISSUE THREAD

**Issue by twatzl** [fluhus/gostuff#1]
Hello,

I have checked the documentation on GoDoc, but I could not find any hints to how I can achieve something as described in this SO comment https://stackoverflow.com/questions/12935936/how-to-programmatically-access-wordnet-hierarchy

How can I use your library to query hypernyms if I have a given synset?

And sorry if I get anything conceptually wrong here, this whole wordnet thing is still a bit voodoo magic to me.

Kind Regards!

**Comment by fluhus** [comment]
Hi,

This is possible with the [Pointer](https://godoc.org/github.com/fluhus/gostuff/nlp/wordnet#Pointer) field of Synset.

A typical query should look like:

```go
var ss *Synset // Assign current synset.
var hypernyms []string{} // Synset IDs of ss's hypernyms
for _, p := range ss.Pointer {
  if p.Symbol == wordnet.Hypernym {
    hypernyms = append(hypernyms, p.Synset)
  }
}
```

I hope that helps. Let me know if you have further questions!

**Comment by twatzl** [comment]
Thanks. It worked perfectly.

Using your example I wrote the following function which returns all hypernyms of a given synset.

```
func loadAncestorLabelsForSynset(wn *wordnet.WordNet, synset *wordnet.Synset) []string {
	hypernyms := []string{} // Synset IDs of hypernyms

	synsetsToSearch := []*wordnet.Synset{synset}

	for len(synsetsToSearch) > 0 {
		// deque next element from synsets
		synset = synsetsToSearch[0]
		synsetsToSearch[0] = nil // Erase element (write zero value) to avoid memory leaks
		synsetsToSearch = synsetsToSearch[1:]

		for _, p := range synset.Pointer {
			if p.Symbol == wordnet.Hypernym {
				synsetId := p.Synset
				hypernymSynset := wn.Synset[synsetId]
				synsetsToSearch = append(synsetsToSearch, hypernymSynset)
				hypernyms = append(hypernyms, hypernymSynset.Word[0])
			}
		}
	}

	return hypernyms
}
```

The queue style use of the slice is probably not the most efficient, but it does the job fine.

Have you considered adding the code you wrote as an example to the documentation? That might help newcomers a lot.

**Comment by fluhus** [comment]
Thanks for the feedback, I will add this example to the documentation.

Your piece of code looks good. A few small improvements I can suggest:

1. `hypernyms` says it's synsets but you are adding words to it. You probably want to change either the comment or the values you are adding.
1. You may have duplicates in the result because the wordnet topology might allow several paths to reach the same top hypernym. Consider using `map[string]interface{}` (effectively a set of strings) instead of `[]string`.
1. `synsetsToSearch[0] = nil` is unnecessary because the whole slice becomes garbage when the function ends. Your calls to append also re-allocate the slice as the function progresses, so it shouldn't accumulate old entries as it goes.
1. `Word[0]` might not be the correct word. Consider using the pointer's target word.
1. If you want to be more precise, you could look only at the pointers who's source equals the target of their hyponym (not implemented below).

Consider this alternative version:

```go
func loadAncestorLabelsForSynset(wn *wordnet.WordNet, synset *wordnet.Synset) map[string]interface{} {
	hypernyms := map[string]interface{} // Hypernym words

	synsetsToSearch := []*wordnet.Synset{synset}

	for len(synsetsToSearch) > 0 {
		// deque next element from synsets
		synset = synsetsToSearch[0]
		synsetsToSearch = synsetsToSearch[1:]

		for _, p := range synset.Pointer {
			if p.Symbol != wordnet.Hypernym { // More go-ish, less nesting like this :)
				continue
			}
			synsetId := p.Synset
			hypernymSynset := wn.Synset[synsetId]
			synsetsToSearch = append(synsetsToSearch, hypernymSynset)
			word := hypernymSynset.Word[0]
			if p.Target != -1 { // -1 means the entire synset
				word = hypernymSynset.Word[p.Target]
			}
			hypernyms[word] = interface{}{} // Effectively adds word to the set
		}
	}

	return hypernyms
}
```

Hope it helps.

**Comment by twatzl** [comment]
Thank you for the feedback it was very helpful.

I added a conversion back to a slice and it seems that you cannot instantiate the interface, so I just use empty strings.
